### ISSUE TITLE
Examples: panel that visualize time series data

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#11]
### Description
Create a plugin that contains a panel with custom configuration. This should be an example of how to create a basic panel without any advance functionality. 

### Tasks
- [x] Panel plugin
   - [x] Showcase how add custom configuration for panel.
   - [x] Showcase how use custom configuration in panel.
   - [x] Showcase how to use grafana-ui time series visualization.
   - [x] Showcase how to update time range for dashboard programmatically from panel.
   - [x] Showvase how to read time range from dashboard.
