### ISSUE TITLE
Examples: app with several pages

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#12]
**Related pull request(s):** https://github.com/grafana/grafana-plugin-examples/pull/26

### Description
Create a plugin that contains an app with several pages. This should be an example of how to create a basic app without any advance functionality. 

### Tasks
- [x] Root page with routing (**Done in** https://github.com/grafana/grafana-plugin-examples/pull/26)
   - [x] Showcase how create page with tabs.
   - [x] Showcase how create page without tabs.
   - [x] Showcase how create full width page.
   - [x] Showcase how to navigate between pages.
- [x] Configuration page. (**Done in** https://github.com/grafana/grafana-plugin-examples/pull/26)
   - [x] Showcase how to manage secrets e.g. API keys etc.
   - [x] Showcase how to use the form components.
- [x] #53 (**Done in** https://github.com/grafana/grafana-plugin-examples/pull/92)
