### ISSUE TITLE
Remove usage of `LegacyForms` from examples

### ISSUE THREAD

**Issue by academo** [grafana/grafana-plugin-examples#126]
Many examples use `LegacyForms` to construct the query editor and configuration UI. We should instead use the grafana/ui forms available https://developers.grafana.com/ui/canary/index.html?path=/docs/forms-form--basic
```[tasklist]
### Tasks
- [ ] update datasource-http
- [ ] update datasource-basic
- [ ] udpate datasource-streaming-websocket
```
