### ISSUE TITLE
Examples: datasource with support for annotations

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#13]
### Description
Create a plugin that contains a datasource with backend that returns static data regardless of the query parameters. This should be an example of how to create datasource that supports annotations. 

It can use the: https://github.com/grafana/plugins-examples/issues/1 as a base but enhance it with support for annotations. 

### Tasks
- [ ] A annotations query editor.
   - [ ] Showcase how to use the grafana-ui form components.
- [ ] A datasource with backend
   - [ ] Showcase how to support annotations.
- [ ] Integration tests that verifies that the features that being used from Grafana plugin API is working as expected.

**Comment by academo** [comment]
We are no longer writing examples to demonstrate code and instead prefer to write documentation about the topics. 

Since this repository example's are now auto generated from create-plugin I am closing this issues.
