### ISSUE TITLE
Examples: datasource with backend

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#14]
### Description
Create a plugin that contains a datasource with backend that returns static data regardless of the query parameters. This should be an example of how to create a basic datasource without to advance functionality. 

### Tasks
- [x] A configuration editor.
   - [x] Showcase how to use the grafana-ui form components.
   - [x] Showcase how to configure credentials/secret information.
   - [x] Showcase how to configure regular settings.
- [x] A query editor.
   - [x] Showcase how to query support data used in the editor.
   - [x] Showcase how to use the grafana-ui form components.
   - [x] Showcase how to support template variables.
- [x] A datasource with backend
   - [x] Showcase how to support template variables/macros.
   - [x] Showcase how to query data.
- [ ] ~~Integration tests that verifies that the features that being used from Grafana plugin API is working as expected.~~

**Comment by mckn** [comment]
Closed by #16
