### ISSUE TITLE
EPIC: update samples for Grafana 10

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana-plugin-examples#152]
With the upcoming release of Grafana 10, we should ensure that our samples are up to date and ready for plugin developers to consume.

Tasks:
- [ ] Assess current examples to identify any **significant** changes required and update this task list accordingly
- [x] Branch at v9 as per @mckn 's suggestion (Marcus please add details here)
  - [ ] Update readme to make this easy to discover
  - [ ] Clean up redundant branches
  - [ ] Confirm no examples should be deprecated rather than updated
- [ ] Ensure all are using latest go sdk including updating dependabot configuration to automatically do this with future releases 
- [ ] Update dependencies
- [ ] Update actions in `ci.yml` files
- [ ] Add an example of using a UI extension in an App Plugin to the docs (https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-extension-point)
- [ ] Switch to secureJsonFields for `app-with-backend` example ([reference](https://github.com/grafana/grafana-plugin-examples/pull/118#pullrequestreview-1301498776))
- [ ] ...

**Comment by academo** [comment]
https://github.com/grafana/grafana-plugin-examples/pull/185
https://github.com/grafana/grafana-plugin-examples/pull/188
https://github.com/grafana/grafana-plugin-examples/pull/187

Implement all the required changes for this issue. Apologies I didn't see this tracking issue to tag them correctly.
