### ISSUE TITLE
Chore: Update package manager in readme for the examples

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#237]
### Descriptions

Many of our examples has documentation that reference to `yarn` as the package manger even if we have changed to `npm` as the default package manager.

### Todo

- [ ] [App with backend](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-backend)
- [ ] [App with dashboards](https://github.com/grafana/grafana-plugin-examples/blob/main/examples/app-with-dashboards)
- [ ] [Datasource basic](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-basic)
- [ ] [Datasource http backend](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-http-backend)
- [ ] [Datasource streaming backend websocket](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-streaming-backend-websocket) 
- [ ] [Datasource streaming websocket](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-streaming-websocket)
- [ ] [Panel basic](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-basic)
- [ ] [Panel datalinks](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-datalinks)
- [ ] [Panel plotly](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-plotly)
