### ISSUE TITLE
Chore: Migrate E2E tests to grafana/plugin-e2e

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#249]
### Description
This is an "epic" issue where we track the progress of the migration from `@grafana/e2e` and `@grafana/e2e-selectors` to the new and shiny `@grafana/plugin-e2e` package.

### Todo
- [x] https://github.com/grafana/grafana-plugin-examples/pull/251
- [x] https://github.com/grafana/grafana-plugin-examples/pull/252
- [ ] [app-with-dashboards](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-dashboards)
- [ ] [app-with-extension-point](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-extension-point)
- [ ] [app-with-extensions](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-extensions)
- [ ] [app-with-on-behalf-of-auth](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-on-behalf-of-auth)
- [ ] [app-with-scenes](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-scenes)
- [ ] [app-with-service-account](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-service-account)
- [ ] [datasource-basic](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-basic)
- [ ] [datasource-http-backend](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-http-backend)
- [ ] [datasource-http](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-http)
- [ ] [datasource-logs](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-logs)
- [ ] [datasource-streaming-backend-websocket](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-streaming-backend-websocket)
- [ ] [datasource-streaming-websocket](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-streaming-websocket)
- [ ] [panel-basic](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-basic)
- [ ] [panel-datalinks](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-datalinks)

**Comment by sunker** [comment]
Fixed in https://github.com/grafana/grafana-plugin-examples/pull/272
