### ISSUE TITLE
EPIC: Plugin Dependencies Automation

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana-plugin-examples#286]
**Why?**
We should automate updating our plugin examples as much as possible to avoid them becoming stale or developers having issues that are already solved by newer versions that are available.

https://github.com/grafana/grafana-plugin-examples/issues/285#issuecomment-2095964767

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/285
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/307
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/314
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/329
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/354
```

**Comment by Ukochka** [comment]
All the subtasks are done, closing the epic
