### ISSUE TITLE
Examples: setup infrastructure for running tests in examples

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#9]
### Description
We need to setup a shared infrastructure that will run the integration tests for each example against `latest` and `next` release of Grafana.

Below is a suggestion on how to run the examples.

For each example: 
- Start Grafana in a docker container and pre-install the plugin we want to test. 
- Provide a test dashboard/configuration via provisioning.
- Run integration tests written for the example against the Grafana instance running in docker.

### Things to consider
Each examples integration tests should:
- Build with the **provided version** of Grafana packages and test against **provided version** of Grafana
_(to assert the plugin works with its expected versions)_
- Build with the **provided version** of Grafana packages and test against **latest version** of Grafana 
_(to check if we can run with latest packages provided by Grafana core)_
- Build with the **latest version** of Grafana packages and test against **latest version** of Grafana 
_(to check if we can update the Grafana packages in the plugin example)_

### Tasks
- [x] Scaffold infrastructure for integration testing (#44)
- [x] Integration tests for basic panel that verifies that the features that being used from Grafana plugin API is working as expected. (#55)
- [x] Integration tests for basic datasource that verifies that the features that being used from Grafana plugin API is working as expected. (#45)

**Comment by jackw** [comment]
Closing this now as the three tasks mentioned in the description are done. 🚀 🥳
